### PR TITLE
update packages for node v5

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by furier** [comment]
Have you tested this thoroughly?

**Comment by OmgImAlexis** [comment]
Not really but this is the only way to get it to run on node v5+ and npm v3+.

This should be the base for moving to node v5.

**Comment by OmgImAlexis** [comment]
I'll I'm getting now is this when I try to do `npm install`.
````
> gulp dist

[14:32:23] Using gulpfile ~/code/websync/gulpfile.js
[14:32:23] Starting 'clean'...
[14:32:23] Starting 'copy-server-to-dist'...
[14:32:23] Finished 'copy-server-to-dist' after 43 ms
[14:32:23] Starting 'browserify'...
[14:32:23] Finished 'browserify' after 14 ms
[14:32:23] Starting 'html'...
[14:32:23] Finished 'html' after 5.72 ms
[14:32:23] Starting 'scss'...
[14:32:23] Finished 'scss' after 7.44 ms
[14:32:23] Starting 'css'...
[14:32:23] Finished 'css' after 19 ms
[14:32:23] Starting 'fonts'...
[14:32:23] Finished 'fonts' after 8.1 ms
[14:32:23] Starting 'imagemin'...
[14:32:23] Finished 'imagemin' after 9.13 ms
[14:32:23] Starting 'bower'...
[14:32:23] Finished 'bower' after 4.25 ms
[14:32:23] Starting 'build'...
[14:32:23] Finished 'build' after 5.93 ms
[14:32:23] Starting 'build-prod'...
[14:32:23] Finished 'build-prod' after 12 μs
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat '/Users/xo/code/websync/dist/assets'
    at Error (native)
sh: line 1: 98504 Segmentation fault: 11  npm run build-dist

npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/xo/.nvm/versions/node/v5.0.0/bin/node" "/Users/xo/.nvm/versions/node/v5.0.0/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! websync@1.0.4 install: `napa && npm run install-bower-dependencies && npm run build-dist`
npm ERR! Exit status 139
npm ERR! 
npm ERR! Failed at the websync@1.0.4 install script 'napa && npm run install-bower-dependencies && npm run build-dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the websync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     napa && npm run install-bower-dependencies && npm run build-dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs websync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls websync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xo/code/websync/npm-debug.log
````

**Comment by sparklyballs** [comment]
i built this using xo's fork in a docker.

https://github.com/sparklyballs/docker-websync/blob/master/Dockerfile

**Comment by furier** [comment]
@sparklyballs hows the fork working?

**Comment by OmgImAlexis** [comment]
@furier should I just close this?

**Comment by furier** [comment]
yeah, I haven't gotten around to test it my self...

man. 10. okt. 2016 kl. 03.26 skrev X O <notifications@github.com>:

**Pull request closed without merging**
